# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20170909_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='services',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
