# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20170912_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('desc', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=5, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Service2',
                'verbose_name': 'Service2',
                'verbose_name_plural': 'Service2',
            },
        ),
        migrations.RenameField(
            model_name='services',
            old_name='type',
            new_name='usertype',
        ),
        migrations.AlterModelTable(
            name='services',
            table='Services',
        ),
    ]
