# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20170914_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='type',
            new_name='usertype',
        ),
        migrations.RenameField(
            model_name='libraries',
            old_name='type',
            new_name='usertype',
        ),
        migrations.RenameField(
            model_name='malls',
            old_name='type',
            new_name='usertype',
        ),
        migrations.RenameField(
            model_name='museums',
            old_name='type',
            new_name='usertype',
        ),
        migrations.RenameField(
            model_name='parks',
            old_name='type',
            new_name='usertype',
        ),
        migrations.RenameField(
            model_name='restaurants',
            old_name='type',
            new_name='usertype',
        ),
        migrations.RenameField(
            model_name='zoos',
            old_name='type',
            new_name='usertype',
        ),
    ]
